group=com.kiocg.java
version=1.21.8-R0.1-SNAPSHOT
mcVersion=1.21.8
paperRef=29c8822d90899c89d2689338e81a98f690bcba12

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false

systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808
