group=com.kiocg.java
version=1.21.6-R0.1-SNAPSHOT
mcVersion=1.21.6
paperRef=4d854e66b80dad9898d71a0f0b1f83cd39b97119

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false

systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10809
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10809
